INSERT INTO currencies (code, name, symbol)
VALUES ('USD', 'US Dollar', '$'),
       ('EUR', 'Euro', '€'),
       ('GBP', 'British Pound', '£'),
       ('JPY', 'Japanese Yen', '¥'),
       ('NGN', 'Nigerian Naira', '₦'),
       ('INR', 'Indian Rupee', '₹'),
       ('CNY', 'Chinese Yuan', '¥'),
       ('AUD', 'Australian Dollar', 'A$'),
       ('CAD', 'Canadian Dollar', 'C$'),
       ('ZAR', 'South African Rand', 'R'),
       ('BRL', 'Brazilian Real', 'R$'),
       ('KES', 'Kenyan Shilling', 'KSh'),
       ('GHS', 'Ghanaian Cedi', 'GH₵'),
       ('SGD', 'Singapore Dollar', 'S$'),
       ('CHF', 'Swiss Franc', 'CHF'),
       ('MXN', 'Mexican Peso', 'MX$'),
       ('PHP', 'Philippine Peso', '₱'),
       ('SEK', 'Swedish Krona', 'kr'),
       ('NOK', 'Norwegian Krone', 'kr'),
       ('DKK', 'Danish Krone', 'kr'),
       ('PLN', 'Polish Zloty', 'zł'),
       ('THB', 'Thai Baht', '฿'),
       ('RUB', 'Russian Ruble', '₽'),
       ('KRW', 'South Korean Won', '₩'),
       ('MYR', 'Malaysian Ringgit', 'RM'),
       ('HKD', 'Hong Kong Dollar', 'HK$'),
       ('NZD', 'New Zealand Dollar', 'NZ$'),
       ('IDR', 'Indonesian Rupiah', 'Rp'),
       ('EGP', 'Egyptian Pound', 'E£'),
       ('AED', 'United Arab Emirates Dirham', 'د.إ'),
       ('SAR', 'Saudi Riyal', '﷼'),
       ('QAR', 'Qatari Riyal', '﷼'),
       ('OMR', 'Omani Rial', '﷼'),
       ('BHD', 'Bahraini Dinar', 'BD'),
       ('KWD', 'Kuwaiti Dinar', 'KD'),
       ('PKR', 'Pakistani Rupee', '₨'),
       ('BDT', 'Bangladeshi Taka', '৳'),
       ('LKR', 'Sri Lankan Rupee', 'Rs'),
       ('VND', 'Vietnamese Dong', '₫'),
       ('ARS', 'Argentine Peso', 'AR$'),
       ('CLP', 'Chilean Peso', 'CL$'),
       ('COP', 'Colombian Peso', 'COL$'),
       ('UYU', 'Uruguayan Peso', 'UY$'),
       ('PEN', 'Peruvian Sol', 'S/'),
       ('BOB', 'Bolivian Boliviano', 'Bs.'),
       ('PYG', 'Paraguayan Guarani', '₲'),
       ('HUF', 'Hungarian Forint', 'Ft'),
       ('CZK', 'Czech Koruna', 'Kč'),
       ('RON', 'Romanian Leu', 'lei'),
       ('BGN', 'Bulgarian Lev', 'лв'),
       ('HRK', 'Croatian Kuna', 'kn'),
       ('ISK', 'Icelandic Krona', 'kr'),
       ('UAH', 'Ukrainian Hryvnia', '₴'),
       ('GEL', 'Georgian Lari', '₾'),
       ('MDL', 'Moldovan Leu', 'L'),
       ('RSD', 'Serbian Dinar', 'дин'),
       ('MKD', 'Macedonian Denar', 'ден'),
       ('DZD', 'Algerian Dinar', 'دج'),
       ('TND', 'Tunisian Dinar', 'د.ت'),
       ('MAD', 'Moroccan Dirham', 'د.م.'),
       ('XOF', 'West African CFA Franc', 'CFA'),
       ('XAF', 'Central African CFA Franc', 'CFA'),
       ('MGA', 'Malagasy Ariary', 'Ar'),
       ('MZN', 'Mozambican Metical', 'MT'),
       ('ZMW', 'Zambian Kwacha', 'ZK'),
       ('MWK', 'Malawian Kwacha', 'MK'),
       ('UGX', 'Ugandan Shilling', 'USh'),
       ('TZS', 'Tanzanian Shilling', 'TSh'),
       ('ETB', 'Ethiopian Birr', 'Br'),
       ('SDG', 'Sudanese Pound', 'SDG'),
       ('SSP', 'South Sudanese Pound', '£'),
       ('LRD', 'Liberian Dollar', 'L$'),
       ('SLL', 'Sierra Leonean Leone', 'Le'),
       ('XCD', 'East Caribbean Dollar', 'EC$'),
       ('JMD', 'Jamaican Dollar', 'J$'),
       ('TTD', 'Trinidad and Tobago Dollar', 'TT$'),
       ('BBD', 'Barbadian Dollar', 'Bds$'),
       ('BZD', 'Belize Dollar', 'BZ$'),
       ('BSD', 'Bahamian Dollar', 'B$'),
       ('CUP', 'Cuban Peso', '₱'),
       ('DOP', 'Dominican Peso', 'RD$'),
       ('HTG', 'Haitian Gourde', 'G'),
       ('SRD', 'Surinamese Dollar', 'SRD$'),
       ('BMD', 'Bermudian Dollar', 'BD$'),
       ('ANG', 'Netherlands Antillean Guilder', 'ƒ'),
       ('AWG', 'Aruban Florin', 'ƒ'),
       ('FKP', 'Falkland Islands Pound', '£'),
       ('GIP', 'Gibraltar Pound', '£'),
       ('SHP', 'Saint Helena Pound', '£'),
       ('IMP', 'Isle of Man Pound', '£'),
       ('JEP', 'Jersey Pound', '£'),
       ('GGP', 'Guernsey Pound', '£'),
       ('TVD', 'Tuvaluan Dollar', 'TVD$'),
       ('FJD', 'Fijian Dollar', 'FJ$'),
       ('PGK', 'Papua New Guinean Kina', 'K'),
       ('WST', 'Samoan Tala', 'WS$'),
       ('TOP', 'Tongan Paʻanga', 'T$'),
       ('KID', 'Kiribati Dollar', 'K$'),
       ('VUV', 'Vanuatu Vatu', 'Vt'),
       ('BTN', 'Bhutanese Ngultrum', 'Nu.'),
       ('MVR', 'Maldivian Rufiyaa', 'MVR'),
       ('LAK', 'Lao Kip', '₭');
