INSERT INTO categories (display_name, name, description)
VALUES ('Rent/Mortgage', 'housing_rent', 'Monthly rent or mortgage payments'),
       ('Utilities', 'housing_utilities', 'Electricity, water, gas, and other utilities'),
       ('Internet & Cable', 'housing_internet', 'Internet and cable TV expenses'),
       ('Fuel', 'transport_fuel', 'Fuel for personal vehicles'),
       ('Public Transport', 'transport_public', 'Bus, train, taxi, and rideshare expenses'),
       ('Vehicle Maintenance', 'transport_maintenance', 'Car servicing, repairs, and insurance'),
       ('Groceries', 'food_groceries', 'Supermarket and grocery store expenses'),
       ('Dining Out', 'food_dining', 'Restaurants, fast food, and takeout'),
       ('Coffee & Snacks', 'food_coffee', 'Cafes, snacks, and beverages'),
       ('Health Insurance', 'health_insurance', 'Monthly health insurance premiums'),
       ('Medical Bills', 'health_medical', 'Doctor visits, prescriptions, and medical treatments'),
       ('Fitness & Gym', 'health_fitness', 'Gym memberships and fitness-related costs'),
       ('Movies & Streaming', 'entertainment_movies', 'Cinema tickets and streaming subscriptions'),
       ('Hobbies', 'entertainment_hobbies', 'Books, music, arts, and other hobbies'),
       ('Events & Concerts', 'entertainment_events', 'Concerts, sports, and entertainment events'),
       ('Loan Repayments', 'debt_loans', 'Monthly loan payments'),
       ('Credit Card Bills', 'debt_credit_cards', 'Credit card payments and interest'),
       ('Emergency Fund', 'savings_emergency', 'Savings for unexpected expenses'),
       ('Retirement Savings', 'savings_retirement', 'Funds for future retirement plans'),
       ('Tuition', 'education_tuition', 'School and university tuition fees'),
       ('Books & Courses', 'education_books', 'Educational books, courses, and training materials'),
       ('Clothing', 'personal_clothing', 'Shopping for clothes and accessories'),
       ('Haircuts & Beauty', 'personal_beauty', 'Salon, haircuts, and beauty treatments'),
       ('Charity', 'gifts_charity', 'Donations to charitable organizations'),
       ('Gifts', 'gifts_general', 'Birthday and holiday gifts for family and friends'),
       ('Other Expenses', 'misc_other', 'Uncategorized expenses');